// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: connection/pb/coms.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Message_Direction int32

const (
	Message_STEADY Message_Direction = 0
	Message_UP     Message_Direction = 1
	Message_DOWN   Message_Direction = 2
	Message_LEFT   Message_Direction = 3
	Message_RIGHT  Message_Direction = 4
)

// Enum value maps for Message_Direction.
var (
	Message_Direction_name = map[int32]string{
		0: "STEADY",
		1: "UP",
		2: "DOWN",
		3: "LEFT",
		4: "RIGHT",
	}
	Message_Direction_value = map[string]int32{
		"STEADY": 0,
		"UP":     1,
		"DOWN":   2,
		"LEFT":   3,
		"RIGHT":  4,
	}
)

func (x Message_Direction) Enum() *Message_Direction {
	p := new(Message_Direction)
	*p = x
	return p
}

func (x Message_Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Message_Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_connection_pb_coms_proto_enumTypes[0].Descriptor()
}

func (Message_Direction) Type() protoreflect.EnumType {
	return &file_connection_pb_coms_proto_enumTypes[0]
}

func (x Message_Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Message_Direction.Descriptor instead.
func (Message_Direction) EnumDescriptor() ([]byte, []int) {
	return file_connection_pb_coms_proto_rawDescGZIP(), []int{0, 0}
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TankState       uint32                  `protobuf:"varint,1,opt,name=tankState,proto3" json:"tankState,omitempty"`
	TankPosition    *Message_TankPosition   `protobuf:"bytes,2,opt,name=tankPosition,proto3" json:"tankPosition,omitempty"`
	BulletState     uint32                  `protobuf:"varint,3,opt,name=bulletState,proto3" json:"bulletState,omitempty"`
	BulletPosition  *Message_BulletPosition `protobuf:"bytes,4,opt,name=bulletPosition,proto3" json:"bulletPosition,omitempty"`
	BulletDirection Message_Direction       `protobuf:"varint,5,opt,name=bulletDirection,proto3,enum=battle_city_ds.Message_Direction" json:"bulletDirection,omitempty"`
	Action          []*Message_Action       `protobuf:"bytes,6,rep,name=action,proto3" json:"action,omitempty"`
	Host            string                  `protobuf:"bytes,7,opt,name=host,proto3" json:"host,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connection_pb_coms_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_connection_pb_coms_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_connection_pb_coms_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetTankState() uint32 {
	if x != nil {
		return x.TankState
	}
	return 0
}

func (x *Message) GetTankPosition() *Message_TankPosition {
	if x != nil {
		return x.TankPosition
	}
	return nil
}

func (x *Message) GetBulletState() uint32 {
	if x != nil {
		return x.BulletState
	}
	return 0
}

func (x *Message) GetBulletPosition() *Message_BulletPosition {
	if x != nil {
		return x.BulletPosition
	}
	return nil
}

func (x *Message) GetBulletDirection() Message_Direction {
	if x != nil {
		return x.BulletDirection
	}
	return Message_STEADY
}

func (x *Message) GetAction() []*Message_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *Message) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type Message_TankPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X uint32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y uint32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Message_TankPosition) Reset() {
	*x = Message_TankPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connection_pb_coms_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message_TankPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_TankPosition) ProtoMessage() {}

func (x *Message_TankPosition) ProtoReflect() protoreflect.Message {
	mi := &file_connection_pb_coms_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_TankPosition.ProtoReflect.Descriptor instead.
func (*Message_TankPosition) Descriptor() ([]byte, []int) {
	return file_connection_pb_coms_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Message_TankPosition) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Message_TankPosition) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Message_BulletPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X uint32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y uint32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Message_BulletPosition) Reset() {
	*x = Message_BulletPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connection_pb_coms_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message_BulletPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_BulletPosition) ProtoMessage() {}

func (x *Message_BulletPosition) ProtoReflect() protoreflect.Message {
	mi := &file_connection_pb_coms_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_BulletPosition.ProtoReflect.Descriptor instead.
func (*Message_BulletPosition) Descriptor() ([]byte, []int) {
	return file_connection_pb_coms_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Message_BulletPosition) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Message_BulletPosition) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Message_Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	TankDirection Message_Direction    `protobuf:"varint,2,opt,name=tankDirection,proto3,enum=battle_city_ds.Message_Direction" json:"tankDirection,omitempty"`
}

func (x *Message_Action) Reset() {
	*x = Message_Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connection_pb_coms_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message_Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Action) ProtoMessage() {}

func (x *Message_Action) ProtoReflect() protoreflect.Message {
	mi := &file_connection_pb_coms_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Action.ProtoReflect.Descriptor instead.
func (*Message_Action) Descriptor() ([]byte, []int) {
	return file_connection_pb_coms_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Message_Action) GetTs() *timestamp.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Message_Action) GetTankDirection() Message_Direction {
	if x != nil {
		return x.TankDirection
	}
	return Message_STEADY
}

var File_connection_pb_coms_proto protoreflect.FileDescriptor

var file_connection_pb_coms_proto_rawDesc = []byte{
	0x0a, 0x18, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x2f,
	0x63, 0x6f, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x62, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x5f, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x64, 0x73, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x95, 0x05, 0x0a, 0x07, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x61, 0x6e, 0x6b, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x74, 0x61, 0x6e, 0x6b, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x48, 0x0a, 0x0c, 0x74, 0x61, 0x6e, 0x6b, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x5f, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x64, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x54, 0x61, 0x6e, 0x6b, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c,
	0x74, 0x61, 0x6e, 0x6b, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b,
	0x62, 0x75, 0x6c, 0x6c, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0b, 0x62, 0x75, 0x6c, 0x6c, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x4e,
	0x0a, 0x0e, 0x62, 0x75, 0x6c, 0x6c, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f,
	0x63, 0x69, 0x74, 0x79, 0x5f, 0x64, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x42, 0x75, 0x6c, 0x6c, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e,
	0x62, 0x75, 0x6c, 0x6c, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x4b,
	0x0a, 0x0f, 0x62, 0x75, 0x6c, 0x6c, 0x65, 0x74, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x5f, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x64, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0f, 0x62, 0x75, 0x6c, 0x6c,
	0x65, 0x74, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x36, 0x0a, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x62, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x5f, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x64, 0x73, 0x2e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x1a, 0x2a, 0x0a, 0x0c, 0x54, 0x61, 0x6e, 0x6b, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x01, 0x79, 0x1a, 0x2c, 0x0a, 0x0e, 0x42, 0x75, 0x6c, 0x6c, 0x65, 0x74, 0x50, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01,
	0x79, 0x1a, 0x7d, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x02, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x47, 0x0a, 0x0d, 0x74, 0x61, 0x6e, 0x6b, 0x44,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21,
	0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x64, 0x73, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x0d, 0x74, 0x61, 0x6e, 0x6b, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x3e, 0x0a, 0x09, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0a, 0x0a,
	0x06, 0x53, 0x54, 0x45, 0x41, 0x44, 0x59, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x55, 0x50, 0x10,
	0x01, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x4c,
	0x45, 0x46, 0x54, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x49, 0x47, 0x48, 0x54, 0x10, 0x04,
	0x32, 0x45, 0x0a, 0x04, 0x43, 0x6f, 0x6d, 0x73, 0x12, 0x3d, 0x0a, 0x0a, 0x61, 0x64, 0x64, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x17, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f,
	0x63, 0x69, 0x74, 0x79, 0x5f, 0x64, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x07, 0x5a, 0x05, 0x70, 0x62, 0x3b, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_connection_pb_coms_proto_rawDescOnce sync.Once
	file_connection_pb_coms_proto_rawDescData = file_connection_pb_coms_proto_rawDesc
)

func file_connection_pb_coms_proto_rawDescGZIP() []byte {
	file_connection_pb_coms_proto_rawDescOnce.Do(func() {
		file_connection_pb_coms_proto_rawDescData = protoimpl.X.CompressGZIP(file_connection_pb_coms_proto_rawDescData)
	})
	return file_connection_pb_coms_proto_rawDescData
}

var file_connection_pb_coms_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_connection_pb_coms_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_connection_pb_coms_proto_goTypes = []interface{}{
	(Message_Direction)(0),         // 0: battle_city_ds.Message.Direction
	(*Message)(nil),                // 1: battle_city_ds.Message
	(*Message_TankPosition)(nil),   // 2: battle_city_ds.Message.TankPosition
	(*Message_BulletPosition)(nil), // 3: battle_city_ds.Message.BulletPosition
	(*Message_Action)(nil),         // 4: battle_city_ds.Message.Action
	(*timestamp.Timestamp)(nil),    // 5: google.protobuf.Timestamp
	(*empty.Empty)(nil),            // 6: google.protobuf.Empty
}
var file_connection_pb_coms_proto_depIdxs = []int32{
	2, // 0: battle_city_ds.Message.tankPosition:type_name -> battle_city_ds.Message.TankPosition
	3, // 1: battle_city_ds.Message.bulletPosition:type_name -> battle_city_ds.Message.BulletPosition
	0, // 2: battle_city_ds.Message.bulletDirection:type_name -> battle_city_ds.Message.Direction
	4, // 3: battle_city_ds.Message.action:type_name -> battle_city_ds.Message.Action
	5, // 4: battle_city_ds.Message.Action.ts:type_name -> google.protobuf.Timestamp
	0, // 5: battle_city_ds.Message.Action.tankDirection:type_name -> battle_city_ds.Message.Direction
	1, // 6: battle_city_ds.Coms.addMessage:input_type -> battle_city_ds.Message
	6, // 7: battle_city_ds.Coms.addMessage:output_type -> google.protobuf.Empty
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_connection_pb_coms_proto_init() }
func file_connection_pb_coms_proto_init() {
	if File_connection_pb_coms_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_connection_pb_coms_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connection_pb_coms_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message_TankPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connection_pb_coms_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message_BulletPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connection_pb_coms_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message_Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_connection_pb_coms_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_connection_pb_coms_proto_goTypes,
		DependencyIndexes: file_connection_pb_coms_proto_depIdxs,
		EnumInfos:         file_connection_pb_coms_proto_enumTypes,
		MessageInfos:      file_connection_pb_coms_proto_msgTypes,
	}.Build()
	File_connection_pb_coms_proto = out.File
	file_connection_pb_coms_proto_rawDesc = nil
	file_connection_pb_coms_proto_goTypes = nil
	file_connection_pb_coms_proto_depIdxs = nil
}
