// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ComsClient is the client API for Coms service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ComsClient interface {
	AddMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*empty.Empty, error)
}

type comsClient struct {
	cc grpc.ClientConnInterface
}

func NewComsClient(cc grpc.ClientConnInterface) ComsClient {
	return &comsClient{cc}
}

func (c *comsClient) AddMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/battle_city_ds.Coms/addMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComsServer is the server API for Coms service.
// All implementations must embed UnimplementedComsServer
// for forward compatibility
type ComsServer interface {
	AddMessage(context.Context, *Message) (*empty.Empty, error)
	mustEmbedUnimplementedComsServer()
}

// UnimplementedComsServer must be embedded to have forward compatible implementations.
type UnimplementedComsServer struct {
}

func (UnimplementedComsServer) AddMessage(context.Context, *Message) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMessage not implemented")
}
func (UnimplementedComsServer) mustEmbedUnimplementedComsServer() {}

// UnsafeComsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComsServer will
// result in compilation errors.
type UnsafeComsServer interface {
	mustEmbedUnimplementedComsServer()
}

func RegisterComsServer(s *grpc.Server, srv ComsServer) {
	s.RegisterService(&_Coms_serviceDesc, srv)
}

func _Coms_AddMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComsServer).AddMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/battle_city_ds.Coms/AddMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComsServer).AddMessage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

var _Coms_serviceDesc = grpc.ServiceDesc{
	ServiceName: "battle_city_ds.Coms",
	HandlerType: (*ComsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "addMessage",
			Handler:    _Coms_AddMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "connection/pb/coms.proto",
}
